Merged PR 16383: build: Update botocore dependency to version 1.35.99
Fix mismatch

```
ERROR: Cannot install -r requirements.txt (line 1) and botocore==1.35.97 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested botocore==1.35.97
    boto3 1.35.99 depends on botocore<1.36.0 and >=1.35.99
```